[package]
name = "distributed-state-machine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tokio = {version = "1.41.0",features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }  # For UUID version 4

